spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clinic?&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 123admin
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: mapper
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  jmx:
    enabled: false

server:
  port: 8080
  #  servlet:
  #    context-path: /cater

  tomcat:
    uri-encoding: UTF-8




