spring:
  datasource:
    username: root
    password: 123admin
    url: jdbc:mysql://127.0.0.1:3306/clinic?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: mapper
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
  jmx:
    enabled: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  port: 8080

  tomcat:
    uri-encoding: UTF-8
#pagehelper:
#  helper-dialect: mysql
#  support-methods-arguments: true
#  params: count=countSql
#mybatis:
#  mapper-locations:  classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    map-underscore-to-camel-case: true


